### ISSUE TITLE
Other choice of words

### ISSUE THREAD

**Issue by erikdubois** [Antergos/antergos-welcome#2]
with the build button you mean install on the harddisk? Then I would use install

**Comment by jkw** [comment]
Build as in a browser opens up and shows the page https://github.com/Antergos to show repositorys with code for the Antergos project.

**Comment by lots0logs** [comment]
I've already change the button to "Bug Reporting" 

Cheers!

**Comment by erikdubois** [comment]
hi dustin,
i am thinking about using  this github for Archlabs - and change some of the elements 
is it all possible?
are you ok with that...? 
there is also an issue mentioned here - is that a problem for the future?
we might also combine our efforts to maintain this github as well
cheers erik
